# Generated by Django 2.1.7 on 2019-04-09 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrarprodukt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrarprodukt', models.CharField(max_length=50)),
                ('los_chargennummer', models.CharField(max_length=50)),
                ('produktionsart', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Anbau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutzflaechennr', models.CharField(max_length=50)),
                ('nutzflaeche', models.CharField(max_length=50)),
                ('agrarprodukt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anbau', to='API.Agrarprodukt')),
                ('verantwortlicher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anbau', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anbaumassnahmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massnahme', models.CharField(max_length=50)),
                ('landwirtschftliches_nutzfahrzeug', models.CharField(max_length=50)),
                ('startuhrzeit_der_bearbeitung', models.CharField(max_length=50)),
                ('anbau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anbaumassnahmen', to='API.Anbau')),
                ('verantwortlicher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anbaumassnahmen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produktname', models.CharField(max_length=50)),
                ('produktbeschreibung', models.TextField(max_length=300)),
                ('agrarprodukt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produkt', to='API.Agrarprodukt')),
                ('produkte', models.ManyToManyField(blank=True, related_name='produkt', to='API.Produkt')),
            ],
        ),
        migrations.CreateModel(
            name='Produktmassnahmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('beschreibung', models.TextField(max_length=300)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produktmassnahmen', to='API.Produkt')),
            ],
        ),
    ]
