# Generated by Django 2.1.7 on 2019-06-24 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrarprodukte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrarprodukt', models.CharField(max_length=50)),
                ('los_chargennummer', models.CharField(max_length=50)),
                ('produktionsart', models.CharField(max_length=50)),
                ('produzent_name', models.CharField(max_length=50)),
                ('produzent_straße', models.CharField(max_length=50)),
                ('produzent_ort', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nutzflaechen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxnummer', models.IntegerField()),
                ('nutzflaechennummer', models.IntegerField()),
                ('kreisnummer', models.IntegerField()),
                ('kreis', models.CharField(max_length=50)),
                ('bundeslandnummer', models.IntegerField()),
                ('bundesland', models.CharField(max_length=50)),
                ('nutzflaeche_in_ha', models.FloatField()),
                ('verantwortlicher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutzflaeche', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nutzflaechenmassnahmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massnahme', models.CharField(max_length=50)),
                ('landwirtschftliches_nutzfahrzeug', models.CharField(max_length=50)),
                ('datum', models.DateTimeField()),
                ('startuhrzeit_der_bearbeitung', models.TimeField()),
                ('enduhrzeit_der_bearbeitung', models.TimeField()),
                ('zeitdifferenz', models.TimeField()),
                ('bearbeitungszeit', models.TimeField()),
                ('unterbrechungszeit', models.TimeField()),
                ('zurückgelegte_strecke_in_km', models.FloatField()),
                ('durchschnittliche_fahrgeschwindigkeit_in_kmh', models.FloatField()),
                ('bearbeitungsbreite_in_m', models.FloatField()),
                ('bearbeitet_nutzfläche_in_ha', models.FloatField()),
                ('flächenleistung_in_hah', models.FloatField()),
                ('ausgeführt_auf_nutzflaeche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutzflaechenmassnahmen', to='API.Nutzflaechen')),
                ('verantwortlicher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutzflaechenmassnahmen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produkte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produktname', models.CharField(max_length=50)),
                ('produktbeschreibung', models.TextField(max_length=300)),
                ('besteht_aus_produkte', models.ManyToManyField(blank=True, related_name='produkt', to='API.Produkte')),
                ('hergestellt_aus_agrarprodukt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wird_verwendet_in_produkte', to='API.Agrarprodukte')),
            ],
        ),
        migrations.CreateModel(
            name='Produktmassnahmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massnahme', models.CharField(max_length=50)),
                ('beschreibung', models.TextField(max_length=300)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produktmassnahmen', to='API.Produkte')),
            ],
        ),
        migrations.AddField(
            model_name='agrarprodukte',
            name='angebaut_auf_nutzflaeche',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agrarprodukt', to='API.Nutzflaechen'),
        ),
    ]
