# Generated by Django 2.1.7 on 2019-06-06 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrarprodukte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrarprodukt', models.CharField(max_length=50)),
                ('los_chargennummer', models.CharField(max_length=50)),
                ('produktionsart', models.CharField(max_length=50)),
                ('produzent_name', models.CharField(max_length=50)),
                ('produzent_straße', models.CharField(max_length=50)),
                ('produzent_ort', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nutzflaechen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxnummer', models.IntegerField()),
                ('nutzflaechennummer', models.IntegerField()),
                ('kreisnummer', models.IntegerField()),
                ('kreis', models.CharField(max_length=50)),
                ('bundeslandnummer', models.IntegerField()),
                ('bundelsland', models.CharField(max_length=50)),
                ('nutzflaeche', models.FloatField()),
                ('agrarprodukt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutzflaeche', to='API.Agrarprodukte')),
                ('verantwortlicher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nutzflaeche', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nutzflaechenmassnahmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massnahme', models.CharField(max_length=50)),
                ('landwirtschftliches_nutzfahrzeug', models.CharField(max_length=50)),
                ('datum', models.DateTimeField()),
                ('startuhrzeit_der_bearbeitung', models.TimeField()),
                ('enduhrzeit_der_bearbeitung', models.TimeField()),
                ('zeitdifferenz', models.TimeField()),
                ('bearbeitungszeit', models.TimeField()),
                ('unterbrechungszeit', models.TimeField()),
                ('zurückgelegte_strecke', models.FloatField()),
                ('durchschnittliche_fahrgeschwindigkeit', models.FloatField()),
                ('bearbeitungsbreite', models.FloatField()),
                ('bearbeitet_nutzfläche', models.FloatField()),
                ('flächenleistung', models.FloatField()),
                ('nutzflaeche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutzflaechenmassnahmen', to='API.Nutzflaechen')),
                ('verantwortlicher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nutzflaechenmassnahmen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produkte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produktname', models.CharField(max_length=50)),
                ('produktbeschreibung', models.TextField(max_length=300)),
                ('agrarprodukt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produkt', to='API.Agrarprodukte')),
                ('produkte', models.ManyToManyField(blank=True, related_name='produkt', to='API.Produkte')),
            ],
        ),
        migrations.CreateModel(
            name='Produktmassnahmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massnahme', models.CharField(max_length=50)),
                ('beschreibung', models.TextField(max_length=300)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produktmassnahmen', to='API.Produkte')),
            ],
        ),
    ]
